# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ftest.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QApplication, QFileDialog
import index
import klasifikasi
import testing
import numpy as np
import sys

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(769, 577)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, -10, 771, 581))
        self.widget.setStyleSheet("background: white;")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 20, 771, 101))
        self.label.setObjectName("label")
        self.plihfile = QtWidgets.QPushButton(self.widget)
        self.plihfile.clicked.connect(self.pildata)
        self.plihfile.setGeometry(QtCore.QRect(520, 260, 101, 41))
        self.plihfile.setStyleSheet("font: 12pt \"Tw Cen MT\";background: #7e7e7e;color: white;")
        self.plihfile.setObjectName("plihfile")
        self.submit = QtWidgets.QPushButton(self.widget)
        self.submit.clicked.connect(self.halaman_klasifikasi)
        self.submit.setGeometry(QtCore.QRect(340, 380, 141, 41))
        self.submit.setStyleSheet("font: 14pt \"Tw Cen MT\";background: #7e7e7e;color: white;text: bold;")
        self.submit.setObjectName("submit")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(230, 170, 301, 31))
        self.label_2.setStyleSheet("font: 75 12pt \"Tw Cen MT\";")
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setGeometry(QtCore.QRect(200, 260, 301, 41))
        self.textEdit.setObjectName("textEdit")
        self.kembali = QtWidgets.QPushButton(self.widget)
        self.kembali.clicked.connect(self.halaman_index)
        self.kembali.setGeometry(QtCore.QRect(620, 500, 131, 41))
        self.kembali.setStyleSheet("font: 12pt \"Tw Cen MT\";background: black;color:white;")
        self.kembali.setObjectName("kembali")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    
    def halaman_index(self): 
        widget1 = QtWidgets.QDialog()
        ui=index.Ui_index()
        ui.setupUi(widget1)
        widget1.show()
        #sys.exit(app.exec_())
        widget1.exec_()

    def pildata(self):
        fname = QFileDialog.getOpenFileName(None, 'Open file', 'D:\coding',"TXT files (*.txt)")
        filePath = fname[0]
        styles = {'color':'r', 'font-size':'10px'}
        self.textEdit.setPlainText(filePath)
    

    def test(self):
        data = self.textEdit.toPlainText()
        kasus, preprocessing, klasif = testing.testing(data)


    def halaman_klasifikasi(self): 
        widget2 = QtWidgets.QDialog()
        ui=klasifikasi.Ui_Form()
        ui.setupUi(widget2)
        widget2.show()
        #sys.exit(app.exec_())
        widget2.exec_()
   

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">KLASIFIKASI JENIS UU ITE MENGGUNAKAN</span></p><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">TEXT MINING PADA KASUS KEJAHATAN SIBER</span></p></body></html>"))
        self.plihfile.setText(_translate("Form", "Pilih File"))
        self.submit.setText(_translate("Form", "SUBMIT"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Masukkan File Kasus Kejahatan Siber</span></p></body></html>"))
        self.kembali.setText(_translate("Form", "KEMBALI"))

def kal():
    data = "D:/coding/dataset/testing/27ayat1_11.txt"
    kasus = testing.isi(data)
    #prepro = testing.preprocessing(kasus)
    #klas =  testing.clas(prepro)

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    app.exec_()
