# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ftest.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets
import index
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QApplication, QFileDialog
import index
import testing
import numpy as np
import sys



class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(809, 639)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(-10, -10, 871, 721))
        self.widget.setStyleSheet("background: white;")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(-40, 10, 891, 101))
        self.label.setObjectName("label")
        self.plihfile = QtWidgets.QPushButton(self.widget)
        self.plihfile.clicked.connect(self.pildata)
        self.plihfile.setGeometry(QtCore.QRect(590, 140, 101, 31))
        self.plihfile.setStyleSheet("font: 12pt \"Tw Cen MT\";background: #7e7e7e;color: white;")
        self.plihfile.setObjectName("plihfile")
        self.submit = QtWidgets.QPushButton(self.widget)
        self.submit.clicked.connect(self.Klasifikasi)
        self.submit.setGeometry(QtCore.QRect(340, 200, 121, 31))
        self.submit.setStyleSheet("font: 14pt \"Tw Cen MT\";background: #7e7e7e;color: white;text: bold;")
        self.submit.setObjectName("submit")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(20, 140, 301, 31))
        self.label_2.setStyleSheet("font: 75 12pt \"Tw Cen MT\";")
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setGeometry(QtCore.QRect(320, 140, 211, 31))
        self.textEdit.setObjectName("textEdit")
        self.kembali = QtWidgets.QPushButton(self.widget)
        self.kembali.clicked.connect(self.halaman_index)
        self.kembali.setGeometry(QtCore.QRect(640, 580, 131, 41))
        self.kembali.setStyleSheet("font: 12pt \"Tw Cen MT\";background: black;color:white;")
        self.kembali.setObjectName("kembali")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(40, 280, 341, 21))
        self.label_5.setStyleSheet("font: 12pt \"Tw Cen MT\";")
        self.label_5.setObjectName("label_5")
        self.isikasus = QtWidgets.QTextEdit(self.widget)
        self.isikasus.setGeometry(QtCore.QRect(35, 310, 351, 201))
        self.isikasus.setStyleSheet("font: 12pt \"Tw Cen MT\";")
        self.isikasus.setObjectName("isikasus")
        self.prepro = QtWidgets.QTextEdit(self.widget)
        self.prepro.setGeometry(QtCore.QRect(440, 310, 351, 201))
        self.prepro.setStyleSheet("font: 12pt \"Tw Cen MT\";")
        self.prepro.setObjectName("prepro")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(440, 280, 351, 21))
        self.label_7.setStyleSheet("font: 12pt \"Tw Cen MT\";")
        self.label_7.setObjectName("label_7")
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setGeometry(QtCore.QRect(40, 540, 191, 31))
        self.label_15.setStyleSheet("font: 12pt \"Tw Cen MT\";")
        self.label_15.setObjectName("label_15")
        self.hasil = QtWidgets.QLabel(self.widget)
        self.hasil.setGeometry(QtCore.QRect(240, 540, 191, 31))
        self.hasil.setStyleSheet("font: 12pt \"Tw Cen MT\";")
        self.hasil.setText("")
        self.hasil.setObjectName("hasil")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def halaman_index(self): 
        widget1 = QtWidgets.QDialog()
        ui=index.Ui_index()
        ui.setupUi(widget1)
        widget1.show()
        #sys.exit(app.exec_())
        widget1.exec_()

    def pildata(self):
        fname = QFileDialog.getOpenFileName(None, 'Open file', 'D:\coding',"TXT files (*.txt)")
        filePath = fname[0]
        styles = {'color':'r', 'font-size':'10px'}
        self.textEdit.setPlainText(filePath)
    

    def Klasifikasi(self):
        data = self.textEdit.toPlainText()
        kasus, preprocessing, clas = testing.test(data)
        self.isikasus.setPlainText(kasus)
        self.prepro.setPlainText(str(preprocessing[0]))
        self.hasil.setText(clas)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">KLASIFIKASI JENIS UU ITE MENGGUNAKAN TEXT MINING PADA </span></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">KASUS KEJAHATAN SIBER</span></p></body></html>"))
        self.plihfile.setText(_translate("Form", "Pilih File"))
        self.submit.setText(_translate("Form", "Klasifikasi"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Masukkan File Kasus Kejahatan Siber</span></p></body></html>"))
        self.kembali.setText(_translate("Form", "KEMBALI"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p align=\"center\">ISI KASUS</p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p align=\"center\">HASIL PREPROCESSING</p></body></html>"))
        self.label_15.setText(_translate("Form", "Kasus Tersebut Terjerat Pasal "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
