# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ftrain.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QApplication, QFileDialog
import index
import train
import halaman_test as test

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(805, 631)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 821, 631))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 101))
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(130, 230, 551, 291))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(120, 0, 301, 31))
        self.label_2.setStyleSheet("font: 75 12pt \"Tw Cen MT\";")
        self.label_2.setObjectName("label_2")
        self.file = QtWidgets.QTextEdit(self.groupBox)
        self.file.setGeometry(QtCore.QRect(90, 60, 251, 31))
        self.file.setObjectName("file")
        self.pilihfile = QtWidgets.QPushButton(self.groupBox)
        self.pilihfile.clicked.connect(self.pildata)
        self.pilihfile.setGeometry(QtCore.QRect(340, 60, 101, 31))
        self.pilihfile.setStyleSheet("font: 12pt \"Tw Cen MT\";\n"
"background: #7e7e7e;\n"
"color: white;")
        self.pilihfile.setObjectName("pilihfile")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(90, 100, 161, 41))
        self.label_3.setStyleSheet("font: 14pt \"Tw Cen MT\";")
        self.label_3.setObjectName("label_3")
        self.select_count = QtWidgets.QTextEdit(self.groupBox)
        self.select_count.setGeometry(QtCore.QRect(250, 110, 191, 31))
        self.select_count.setObjectName("select_count")
        self.traindata = QtWidgets.QPushButton(self.groupBox)
        self.traindata.clicked.connect(self.getTrain)
        self.traindata.setGeometry(QtCore.QRect(200, 170, 121, 31))
        self.traindata.setStyleSheet("background:#6495ED;font: 14pt \"Tw Cen MT\"; color: white;text: bold;")
        self.traindata.setObjectName("traindata")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(70, 240, 141, 31))
        self.label_4.setStyleSheet("font: 12pt \"Tw Cen MT\";")
        self.label_4.setObjectName("label_4")
        self.akurasi = QtWidgets.QLabel(self.groupBox)
        self.akurasi.setGeometry(QtCore.QRect(220, 247, 111, 16))
        self.akurasi.setStyleSheet("font: 12pt \"Tw Cen MT\";")
        self.akurasi.setText("")
        self.akurasi.setObjectName("akurasi")
        self.kembali = QtWidgets.QPushButton(self.widget)
        self.kembali.clicked.connect(self.halaman_index)
        self.kembali.setGeometry(QtCore.QRect(710, 120, 91, 31))
        self.kembali.setStyleSheet("background: #B0E0E6;")
        self.kembali.setObjectName("kembali")
        self.testing = QtWidgets.QPushButton(self.widget)
        self.testing.clicked.connect(self.halamantest)
        self.testing.setGeometry(QtCore.QRect(620, 120, 91, 31))
        self.testing.setStyleSheet("background: #B0E0E6;")
        self.testing.setObjectName("testing")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def halaman_index(self): 
        widget1 = QtWidgets.QDialog()
        ui=index.Ui_index()
        ui.setupUi(widget1)
        widget1.show()
        #sys.exit(app.exec_())
        widget1.exec_()

    def halamantest(self): 
        widget2 = QtWidgets.QDialog()
        ui=test.Ui_Form()
        ui.setupUi(widget2)
        widget2.show()
        #sys.exit(app.exec_())
        widget2.exec_()


    def pildata(self):
        fname = QFileDialog.getOpenFileName(None, 'Open file', 'D:\coding',"CSV files (*.csv)")
        filePath = fname[0]
        styles = {'color':'r', 'font-size':'10px'}
        self.file.setPlainText(filePath)
    
    def getTrain(self):
        data = self.file.toPlainText()
        sc = self.select_count.toPlainText()
        acc= train.tranning(data,int(sc))
        self.akurasi.setText(str(acc*100))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">KLASIFIKASI JENIS UU ITE MENGGUNAKAN</span></p><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">TEXT MINING PADA KASUS KEJAHATAN SIBER</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Masukkan File Kasus Kejahatan Siber</span></p></body></html>"))
        self.pilihfile.setText(_translate("Form", "Pilih File"))
        self.label_3.setText(_translate("Form", "Berikan Jumlah Term:"))
        self.traindata.setText(_translate("Form", "TRAIN DATA"))
        self.label_4.setText(_translate("Form", "Hasil Akurasi Tranning:"))
        self.kembali.setText(_translate("Form", "Kembali"))
        self.testing.setText(_translate("Form", "Testing"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
