# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ftrain.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QApplication, QFileDialog
import index
import train


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(769, 577)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 771, 581))
        self.widget.setStyleSheet("background: white;")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 20, 771, 101))
        self.label.setObjectName("label")
        self.pilihfile = QtWidgets.QPushButton(self.widget)
        self.pilihfile.clicked.connect(self.pildata)
        self.pilihfile.setGeometry(QtCore.QRect(550, 220, 101, 41))
        self.pilihfile.setStyleSheet("font: 12pt \"Tw Cen MT\";background: #7e7e7e;color: white;")
        self.pilihfile.setObjectName("pilihfile")
        self.traindata = QtWidgets.QPushButton(self.widget)
        self.traindata.clicked.connect(self.getTrain)
        self.traindata.setGeometry(QtCore.QRect(300, 380, 171, 41))
        self.traindata.setStyleSheet("font: 14pt \"Tw Cen MT\";background: #7e7e7e; color: white;text: bold;")
        self.traindata.setObjectName("traindata")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(230, 150, 301, 31))
        self.label_2.setStyleSheet("font: 75 12pt \"Tw Cen MT\";")
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setGeometry(QtCore.QRect(210, 220, 301, 41))
        self.textEdit.setObjectName("textEdit")
        self.kembali = QtWidgets.QPushButton(self.widget)
        self.kembali.clicked.connect(self.halaman_index)
        self.kembali.setGeometry(QtCore.QRect(620, 510, 131, 41))
        self.kembali.setStyleSheet("font: 12pt \"Tw Cen MT\";background: black;color:white;")
        self.kembali.setObjectName("kembali")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(210, 290, 291, 41))
        self.label_3.setStyleSheet("font: 14pt \"Tw Cen MT\";")
        self.label_3.setObjectName("label_3")
        self.MI = QtWidgets.QTextEdit(self.widget)
        self.MI.setGeometry(QtCore.QRect(440, 290, 211, 41))
        self.MI.setObjectName("MI")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(210, 470, 181, 31))
        self.label_4.setStyleSheet("font: 12pt \"Tw Cen MT\";")
        self.label_4.setObjectName("label_4")
        self.akurasi = QtWidgets.QLabel(self.widget)
        self.akurasi.setGeometry(QtCore.QRect(350, 480, 111, 16))
        self.akurasi.setStyleSheet("font: 12pt \"Tw Cen MT\";")
        self.akurasi.setText("")
        self.akurasi.setObjectName("akurasi")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def halaman_index(self): 
        widget2 = QtWidgets.QDialog()
        ui=index.Ui_index()
        ui.setupUi(widget2)
        widget2.show()
        widget2.exec_()

    def pildata(self):
        fname = QFileDialog.getOpenFileName(None, 'Open file', 'D:\coding',"CSV files (*.csv)")
        filePath = fname[0]
        styles = {'color':'r', 'font-size':'10px'}
        self.textEdit.setPlainText(filePath)
    
    def getTrain(self):
        data = self.textEdit.toPlainText()
        sc = self.MI.toPlainText()
        acc= train.tranning(data,int(sc))
        self.akurasi.setText(str(acc))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">KLASIFIKASI JENIS UU ITE MENGGUNAKAN</span></p><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">TEXT MINING PADA KASUS KEJAHATAN SIBER</span></p></body></html>"))
        self.pilihfile.setText(_translate("Form", "Pilih File"))
        self.traindata.setText(_translate("Form", "TRAIN DATA"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Masukkan File Kasus Kejahatan Siber</span></p></body></html>"))
        self.kembali.setText(_translate("Form", "KEMBALI"))
        self.label_3.setText(_translate("Form", "Berikan Jumlah Term:"))
        self.label_4.setText(_translate("Form", "Hasil Akurasi Tranning:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
