# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'halaman1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import halaman_train as train
import halaman_test as test
import sys


class Ui_index(object):
    def setupUi(self, index):
        index.setObjectName("index")
        index.resize(767, 579)
        self.widget = QtWidgets.QWidget(index)
        self.widget.setGeometry(QtCore.QRect(0, -10, 801, 601))
        self.widget.setStyleSheet("background: white;")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 40, 771, 91))
        self.label.setStyleSheet("font:\"Tw Cen MT\";")
        self.label.setObjectName("label")
        self.train = QtWidgets.QPushButton(self.widget)
        self.train.clicked.connect(self.halaman_train)
        self.train.setGeometry(QtCore.QRect(230, 490, 141, 41))
        self.train.setStyleSheet("font: 12pt \"Tw Cen MT\";color:white; background:#00006d;")
        self.train.setObjectName("train")
        self.test = QtWidgets.QPushButton(self.widget)
        self.test.clicked.connect(self.halaman_test)
        self.test.setGeometry(QtCore.QRect(410, 490, 141, 41))
        self.test.setStyleSheet(" font: 12pt \"Tw Cen MT\"; color:white; background:#6c0000;")
        self.test.setObjectName("test")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(290, 190, 191, 201))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/ASUS/Pictures/KKK.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(90, 440, 591, 20))
        self.label_3.setStyleSheet("font: 12pt \"Tw Cen MT\";")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(index)
        QtCore.QMetaObject.connectSlotsByName(index)

    def halaman_train(self): 
        widget1 = QtWidgets.QDialog()
        ui=train.Ui_Form()
        ui.setupUi(widget1)
        widget1.show()
        widget1.exec_()

    def halaman_test(self): 
        widget2 = QtWidgets.QDialog()
        ui=test.Ui_Form()
        ui.setupUi(widget2)
        widget2.show()
        widget2.exec_()

    def retranslateUi(self, index):
        _translate = QtCore.QCoreApplication.translate
        index.setWindowTitle(_translate("index", "Form"))
        self.label.setText(_translate("index", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">KLASIFIKASI JENIS UU ITE MENGGUNAKAN</span></p><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">TEXT MINING PADA KASUS KEJAHATAN SIBER</span></p></body></html>"))
        self.train.setText(_translate("index", "TRANNING"))
        self.test.setText(_translate("index", "TESTING"))
        self.label_3.setText(_translate("index", "<html><head/><body><p align=\"center\">Yunita S Marito Pane-161402130</p></body></html>"))



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    index = QtWidgets.QWidget()
    ui = Ui_index()
    ui.setupUi(index)
    index.show()
    app.exec_()
