# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'klasifikasi.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import index
import ftest as test


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(769, 576)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 771, 581))
        self.widget.setStyleSheet("background:white;")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 30, 771, 20))
        self.label.setStyleSheet("font: 14pt \"Tw Cen MT\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(70, 110, 161, 20))
        self.label_2.setStyleSheet("font: 12pt \"Tw Cen MT\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(70, 280, 181, 16))
        self.label_3.setStyleSheet("font: 12pt \"Tw Cen MT\";")
        self.label_3.setObjectName("label_3")
        self.isikasus = QtWidgets.QTextEdit(self.widget)
        self.isikasus.setPlainText(self.isi)
        self.isikasus.setGeometry(QtCore.QRect(70, 150, 621, 111))
        self.isikasus.setObjectName("isikasus")
        self.hasilpre = QtWidgets.QTextEdit(self.widget)
        self.hasilpre.setGeometry(QtCore.QRect(70, 310, 621, 111))
        self.hasilpre.setObjectName("hasilpre")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(70, 450, 221, 31))
        self.label_4.setStyleSheet("font: 12pt \"Tw Cen MT\";")
        self.label_4.setObjectName("label_4")
        self.hasilklas = QtWidgets.QTextEdit(self.widget)
        self.hasilklas.setGeometry(QtCore.QRect(260, 450, 231, 31))
        self.hasilklas.setObjectName("hasilklas")
        self.kembali = QtWidgets.QPushButton(self.widget)
        self.kembali.clicked.connect(self.halaman_index)
        self.kembali.setGeometry(QtCore.QRect(624, 512, 131, 41))
        self.kembali.setStyleSheet("font: 12pt \"Tw Cen MT\";background: black;color:white;")
        self.kembali.setObjectName("kembali")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        
        
    def isi(self):
        isi = test.klasifikasi()

    def halaman_index(self): 
        widget1 = QtWidgets.QDialog()
        ui=index.Ui_index()
        ui.setupUi(widget1)
        widget1.show()
        widget1.exec_()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">HASIL KLASIFIKASI</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "ISI KASUS"))
        self.label_3.setText(_translate("Form", "HASIL PREPROCESSING"))
        self.label_4.setText(_translate("Form", "Kasus Tersebut Terjerat Pasal "))
        self.kembali.setText(_translate("Form", "KELUAR"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    app.exec_()
